#!/bin/bash
# Builds a list of commands to run that will quickly build all the revisions you need...
git log --pretty="mkdir -p 'metadist/%h' && cp meta/gulpfile.coffee . && cp meta/index.html src/. && rm -rf dist && git checkout %h && gulp build && cp -r dist/* 'metadist/%h'" | tac
